"""Custom Genblaze providers for AWS — Bedrock images, Luma Ray video, Polly speech.

Genblaze ships no AWS adapter, so these implement the SDK's SyncProvider contract
directly. That is the point: the same Pipeline/AgentLoop/fallback machinery drives
AWS exactly like GMI Cloud, which is what "provider-independent pipeline" means.

Both providers persist generated bytes to B2 before returning, so every Asset is
byte-backed with a real sha256 — the condition Genblaze's Manifest.verify()
requires (URL-only assets fail verification, and provider URLs expire).

Region note: Bedrock image AND video run in us-west-2 — that is where the ACTIVE
Stability text-to-image models and Luma Ray live. Nova Canvas/Reel are LEGACY in
every region and refuse InvokeModel. Polly runs in the account's home region.
"""
from __future__ import annotations

import base64
import hashlib
import json
import time
from functools import lru_cache
from typing import Any

from genblaze import Asset, Step
from genblaze_core.exceptions import ProviderError
from genblaze_core.providers.base import SyncProvider

from app.config.settings import settings

# Stability on Bedrock: text-to-image and image-to-image, ACTIVE in us-west-2.
BEDROCK_IMAGE_MODELS = {
    "stability.stable-image-core-v1:1",  # fast/cheap — dev tier
    "stability.sd3-5-large-v1:0",        # highest fidelity — final tier
    "stability.stable-image-ultra-v1:1",
}


@lru_cache(maxsize=1)
def _session():
    import boto3

    return boto3.Session(
        aws_access_key_id=settings.aws_access_key_id,
        aws_secret_access_key=settings.aws_secret_access_key,
        region_name=settings.aws_region,
    )


@lru_cache(maxsize=8)  # bedrock-runtime, polly, s3 across two regions
def _client(service: str, region: str):
    return _session().client(service, region_name=region)


@lru_cache(maxsize=1)
def _b2():
    from genblaze_s3 import S3StorageBackend

    return S3StorageBackend.for_backblaze(
        settings.b2_bucket_intermediate, region=settings.b2_region,
        key_id=settings.b2_key_id, app_key=settings.b2_application_key,
    )


def _persist(data: bytes, key: str, content_type: str) -> tuple[str, str]:
    """Byte-back the asset: store in B2, return (durable_url, sha256).

    Falls back to a data: URL when B2 is unconfigured so local/dev runs still
    produce a verifiable sha256 rather than a dangling provider link.
    """
    digest = hashlib.sha256(data).hexdigest()
    if not settings.b2_configured:
        return f"data:{content_type};base64,{base64.b64encode(data).decode()}", digest
    backend = _b2()
    backend.put(key, data, content_type=content_type)
    return backend.get_url(key, expires_in=86400), digest


class BedrockImageProvider(SyncProvider):
    """Stability image generation on Amazon Bedrock.

    Honors ``step.params['image']`` (a URL) by switching to image-to-image, which
    is how a real travel photo becomes an enhanced scene instead of a fabrication.
    """

    name = "aws-bedrock"

    def generate(self, step: Step, config: Any = None) -> Step:
        if step.model not in BEDROCK_IMAGE_MODELS:
            raise ProviderError(
                f"{step.model} is not an active Bedrock image model; "
                f"expected one of {sorted(BEDROCK_IMAGE_MODELS)}"
            )
        payload: dict[str, Any] = {
            "prompt": step.prompt,
            "mode": "text-to-image",
            "aspect_ratio": step.params.get("aspect_ratio", "16:9"),
            "output_format": "png",
        }
        source = step.params.get("image")
        if source:
            img = self._fetch(source)
            if img is not None:
                payload["mode"] = "image-to-image"
                payload["image"] = base64.b64encode(img).decode()
                payload["strength"] = float(step.params.get("strength", 0.65))
                payload.pop("aspect_ratio", None)  # rejected in image-to-image mode

        try:
            response = _client("bedrock-runtime", settings.bedrock_region).invoke_model(
                modelId=step.model, body=json.dumps(payload)
            )
            body = json.loads(response["body"].read())
        except Exception as exc:
            raise ProviderError(f"Bedrock invoke failed ({step.model}): {exc}") from exc

        images = body.get("images") or []
        if not images:
            reason = body.get("finish_reasons") or body.get("error") or "no images returned"
            raise ProviderError(f"Bedrock returned no image ({step.model}): {reason}")

        data = base64.b64decode(images[0])
        key = f"bedrock/{step.step_id}.png"
        url, digest = _persist(data, key, "image/png")
        step.assets.append(
            Asset(asset_id=f"bedrock-{digest[:12]}", url=url, media_type="image/png",
                  sha256=digest, size_bytes=len(data))
        )
        return step

    @staticmethod
    def _fetch(url: str) -> bytes | None:
        import urllib.request

        try:
            if url.startswith("data:"):
                return base64.b64decode(url.split(",", 1)[1])
            if not url.startswith(("http://", "https://")):
                return None
            with urllib.request.urlopen(url, timeout=60) as r:
                return r.read()
        except Exception:
            return None  # unreachable source photo -> fall back to text-to-image


class LumaRayVideoProvider(SyncProvider):
    """Luma Ray on Bedrock — the only ACTIVE video model on Bedrock (us-west-2).

    Unlike the image and speech APIs this one is asynchronous and writes its
    output to S3, so a staging bucket is required; Bedrock will not hand back
    bytes directly. We poll, pull the object, then persist it to B2 like every
    other asset so the manifest stays byte-backed.

    Text-to-video only. Animating the traveller's real photo needs an
    image-to-video model (Sora, GMI Kling) — Nova Reel would have covered it but
    is LEGACY in all 33 Bedrock regions.
    """

    name = "aws-luma"
    poll_interval = 10.0

    def generate(self, step: Step, config: Any = None) -> Step:
        bucket = settings.aws_staging_bucket
        if not bucket:
            raise ProviderError("AWS_STAGING_BUCKET is required for Luma Ray (async S3 output)")

        rt = _client("bedrock-runtime", settings.bedrock_region)
        try:
            invocation = rt.start_async_invoke(
                modelId=step.model,
                modelInput={"prompt": step.prompt},
                outputDataConfig={"s3OutputDataConfig": {"s3Uri": f"s3://{bucket}/video-out/"}},
            )["invocationArn"]
        except Exception as exc:
            raise ProviderError(f"Luma submit failed ({step.model}): {exc}") from exc

        deadline = time.monotonic() + 600
        status = "InProgress"
        while time.monotonic() < deadline:
            state = rt.get_async_invoke(invocationArn=invocation)
            status = state["status"]
            if status != "InProgress":
                break
            time.sleep(self.poll_interval)
        if status != "Completed":
            raise ProviderError(f"Luma {status}: {state.get('failureMessage', '')[:160]}")

        # Bedrock names the output folder after the invocation id.
        prefix = f"video-out/{invocation.rsplit('/', 1)[-1]}/"
        s3 = _client("s3", settings.bedrock_region)
        objects = s3.list_objects_v2(Bucket=bucket, Prefix=prefix).get("Contents", [])
        mp4 = next((o["Key"] for o in objects if o["Key"].endswith(".mp4")), None)
        if not mp4:
            raise ProviderError(f"Luma completed but produced no mp4 under {prefix}")
        data = s3.get_object(Bucket=bucket, Key=mp4)["Body"].read()

        url, digest = _persist(data, f"luma/{step.step_id}.mp4", "video/mp4")
        step.assets.append(
            Asset(asset_id=f"luma-{digest[:12]}", url=url, media_type="video/mp4",
                  sha256=digest, size_bytes=len(data))
        )
        return step


class PollyTTSProvider(SyncProvider):
    """Narration via Amazon Polly neural voices."""

    name = "aws-polly"

    def generate(self, step: Step, config: Any = None) -> Step:
        voice = step.params.get("voice") or settings.polly_voice
        try:
            response = _client("polly", settings.aws_region).synthesize_speech(
                Text=step.prompt, OutputFormat="mp3", VoiceId=voice,
                Engine=step.params.get("engine", "neural"),
            )
            data = response["AudioStream"].read()
        except Exception as exc:
            raise ProviderError(f"Polly synthesis failed ({voice}): {exc}") from exc

        if not data:
            raise ProviderError("Polly returned empty audio")
        key = f"polly/{step.step_id}.mp3"
        url, digest = _persist(data, key, "audio/mpeg")
        step.assets.append(
            Asset(asset_id=f"polly-{digest[:12]}", url=url, media_type="audio/mpeg",
                  sha256=digest, size_bytes=len(data))
        )
        return step


def aws_configured() -> bool:
    return bool(settings.aws_access_key_id and settings.aws_secret_access_key)
